//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTable.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceSize
    {
        public int AlllowanceSizeID { get; set; }
        public Nullable<System.DateTime> AllowanceDate { get; set; }
        public Nullable<decimal> AllowanceSize1 { get; set; }
        public Nullable<int> AllowanceID { get; set; }
    
        public virtual Allowance Allowance { get; set; }
    }
}
