//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTable.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int OrganizationID { get; set; }
        public string OrganizationFullName { get; set; }
        public string OrganizationEnglishName { get; set; }
        public string OrganizationAbbreviatedName { get; set; }
    }
}
