//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTable.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryID { get; set; }
        public Nullable<System.DateTime> SalaryDate { get; set; }
        public Nullable<decimal> SalarySize { get; set; }
        public Nullable<int> PostID { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
