//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTable.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignatureTabularPart
    {
        public int Nline { get; set; }
        public Nullable<int> SignatureID { get; set; }
        public Nullable<int> WorkerID { get; set; }
    
        public virtual Signature Signature { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
