//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTable.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTable1
    {
        public int StaffTableNumber { get; set; }
        public Nullable<System.DateTime> StaffTableDateStart { get; set; }
        public Nullable<System.DateTime> StaffTableDateEnd { get; set; }
        public Nullable<int> StaffTablePeriod { get; set; }
        public Nullable<int> SignatureID { get; set; }
        public Nullable<bool> isSigned { get; set; }
    }
}
