//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTable.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTableTabularPart
    {
        public int Nline { get; set; }
        public Nullable<int> StaffTableNumber { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<decimal> StaffUnits { get; set; }
        public string Notes { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual StaffTable StaffTable { get; set; }
    }
}
