//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTable.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.SignatureTabularPart = new HashSet<SignatureTabularPart>();
        }
    
        public int WorkerID { get; set; }
        public string WorkerSurname { get; set; }
        public string WorkerName { get; set; }
        public string WorkerPatronimyc { get; set; }
        public Nullable<int> PostID { get; set; }
        public string WorkerLogin { get; set; }
        public string WorkerPassword { get; set; }
        public string WorkerEmail { get; set; }
        public string WorkerEmailPassword { get; set; }
    
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignatureTabularPart> SignatureTabularPart { get; set; }
    }
}
